### ISSUE TITLE
Upgrade to victron-ble 0.8.2

### ISSUE THREAD

**Issue by kroese** [j9brown/victron-hacs#2]
A lot of changes were made to victron-ble that I really want to try out, so could a new version of victron-ble be released (0.8.2) and this repo be updated to point to that new release?

**Comment by j9brown** [comment]
This is already done.  Current version of victron-ble is 0.8.4.

**Comment by j9brown** [comment]
That’s odd.  Are you sure you’re looking at the correct file?

https://github.com/j9brown/victron-hacs/blob/main/custom_components/victron_ble/manifest.json

**Comment by j9brown** [comment]
No worries.  I suspect you’ll be wanting the new Smart Lithium and Smart Protect support in which case some changes need to be made to this project to map the data as Home Assistant sensors which I haven’t done.  Feel free to give it a shot!  (I wish it weren’t quite so tedious to do.)
