### ISSUE TITLE
Support for BSC IP22 12/30...HQ2330HKRRK

### ISSUE THREAD

**Issue by mayberryjp** [j9brown/victron-hacs#4]
Hi,
I started using this integration today . Works great - thank you. 've got HA in my camper van in Japan now!

It's discovering my blue smart device (details in subject line)

I don't see a way to get the advertisement key in the victron connect app. 

Is there any option to get it?

I guess harassing victron is the option?

thanks

**Comment by j9brown** [comment]
See [here](https://github.com/keshavdv/victron-ble?tab=readme-ov-file#fetching-keys) for more information about how to retrieve the keys from the Victron Connect app, assuming that the device supports instant readout.
